### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by 13970252381** [jspark311/Arduino-ADG2128#1]
Why I use ADG 2128_exprese.ino program, compile problem, always header file error

**Comment by jspark311** [comment]
Please re-file the issue in English, or submit a PR so I can understand the problem.
Closing.

**Comment by 13970252381** [comment]
Why I use ADG 2128_exprese.ino program, compile problem, always header file error

**Comment by jspark311** [comment]
Do you need this library?
https://github.com/jspark311/CppPotpourri

If you DO NOT want the dependency, change this line:
https://github.com/jspark311/Arduino-ADG2128/blob/master/src/ADG2128.h#L31

Make it....
    
    #define ADG2128_DEBUG 0

Does that solve it?


PS: Thank you for translating to English. :-)

**Comment by 13970252381** [comment]
Sorry to reply you so late.According to your method is not good, I just keep the function in ADG2128.cpP file, the rest of the function directly deleted.
Adg2128.cpp and ADG2128.h are all commented out about ADG2128_DEBUG, which is useful.

**Comment by 13970252381** [comment]
In addition, I found that the sample code given by ADP8866 was empty, with nothing in it.I wonder if you forgot.

**Comment by jspark311** [comment]
I just pushed a doc change to fix a mistake. But I doubt that is your problem. I can build the example in the repo.

Please post compiler logs?

>ADP8866 was empty, with nothing in it.I wonder if you forgot.

No. Just haven't ported it over from my other code base yet.
